---
title: "All Data Graphs"
author: "Felix Westcott"
date: "18/11/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(readxl)
library(xlsx)
library(dplyr)
library(ggpubr)
library(ggsci)
library(rstatix)
library (cowplot)

setwd('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/OPLA LF vs HF/qPCR')

qPCR_summary <- read_excel("qPCR summary.xlsx", sheet = 3)

qPCR_summary$FA <- as.factor(qPCR_summary$FA)

```


``` {r}
ggbarplot(qPCR_summary, x = "FA", "LC3",
       add = "mean_se", error.plot = "upper_errorbar", palette = "npg", legend = "none", fill = "FA", xlab = "OPLA Concentration (uM)", ylab = "Deltadelta Ct", title = "LC3") +
  scale_y_continuous(expand = c(0,0)) +
theme(axis.text.x = element_text(color = "grey20", size = 16),
axis.text.y = element_text(color = "grey20", size = 16),
axis.title.x = element_text(color = "grey20", size = 18),
axis.title.y = element_text(color = "grey20", size = 18),
plot.title = element_text(color = "grey20", size = 25, face = "bold", hjust = 0.5))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/OPLA LF vs HF/graphs/LC3.png')

ggbarplot(qPCR_summary, x = "FA", "GABARAP",
       add = "mean_se", error.plot = "upper_errorbar", palette = "npg", legend = "none", fill = "FA", xlab = "OPLA Concentration (uM)", ylab = "Deltadelta Ct", title = "GABARAP") +
  scale_y_continuous(expand = c(0,0)) +
theme(axis.text.x = element_text(color = "grey20", size = 16),
axis.text.y = element_text(color = "grey20", size = 16),
axis.title.x = element_text(color = "grey20", size = 18),
axis.title.y = element_text(color = "grey20", size = 18),
plot.title = element_text(color = "grey20", size = 25, face = "bold", hjust = 0.5))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/OPLA LF vs HF/graphs/GABARAP.png')

ggbarplot(qPCR_summary, x = "FA", "SQSTM1",
       add = "mean_se", error.plot = "upper_errorbar", palette = "npg", legend = "none", fill = "FA", xlab = "OPLA Concentration (uM)", ylab = "Deltadelta Ct", title = "p62") +
  scale_y_continuous(expand = c(0,0)) +
theme(axis.text.x = element_text(color = "grey20", size = 16),
axis.text.y = element_text(color = "grey20", size = 16),
axis.title.x = element_text(color = "grey20", size = 18),
axis.title.y = element_text(color = "grey20", size = 18),
plot.title = element_text(color = "grey20", size = 25, face = "bold", hjust = 0.5))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/OPLA LF vs HF/graphs/p62.png')

ggbarplot(qPCR_summary, x = "FA", "ATG5",
       add = "mean_se", error.plot = "upper_errorbar", palette = "npg", legend = "none", fill = "FA",  xlab = "OPLA Concentration (uM)", ylab = "Deltadelta Ct", title = "ATG5") +
  scale_y_continuous(expand = c(0,0)) +
theme(axis.text.x = element_text(color = "grey20", size = 16),
axis.text.y = element_text(color = "grey20", size = 16),
axis.title.x = element_text(color = "grey20", size = 18),
axis.title.y = element_text(color = "grey20", size = 18),
plot.title = element_text(color = "grey20", size = 25, face = "bold", hjust = 0.5))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/OPLA LF vs HF/graphs/ATG5.png')

ggbarplot(qPCR_summary, x = "FA", "ATG7",
       add = "mean_se", error.plot = "upper_errorbar", palette = "npg", legend = "none", fill = "FA", xlab = "OPLA Concentration (uM)", ylab = "Deltadelta Ct", title = "ATG7") +
  scale_y_continuous(expand = c(0,0)) +
theme(axis.text.x = element_text(color = "grey20", size = 16),
axis.text.y = element_text(color = "grey20", size = 16),
axis.title.x = element_text(color = "grey20", size = 18),
axis.title.y = element_text(color = "grey20", size = 18),
plot.title = element_text(color = "grey20", size = 25, face = "bold", hjust = 0.5))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/OPLA LF vs HF/graphs/ATG7.png')

ggbarplot(qPCR_summary, x = "FA", "ATG10",
       add = "mean_se", error.plot = "upper_errorbar", palette = "npg", legend = "none", fill = "FA",   xlab = "OPLA Concentration (uM)", ylab = "Deltadelta Ct", title = "ATG10") +
  scale_y_continuous(expand = c(0,0)) +
theme(axis.text.x = element_text(color = "grey20", size = 16),
axis.text.y = element_text(color = "grey20", size = 16),
axis.title.x = element_text(color = "grey20", size = 18),
axis.title.y = element_text(color = "grey20", size = 18),
plot.title = element_text(color = "grey20", size = 25, face = "bold", hjust = 0.5))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/OPLA LF vs HF/graphs/ATG10.png')

ggbarplot(qPCR_summary, x = "FA", "MAPK8",
       add = "mean_se", error.plot = "upper_errorbar", palette = "npg", legend = "none", fill = "FA",   xlab = "OPLA Concentration (uM)", ylab = "Deltadelta Ct", title = "JNK1") +
  scale_y_continuous(expand = c(0,0)) +
theme(axis.text.x = element_text(color = "grey20", size = 16),
axis.text.y = element_text(color = "grey20", size = 16),
axis.title.x = element_text(color = "grey20", size = 18),
axis.title.y = element_text(color = "grey20", size = 18),
plot.title = element_text(color = "grey20", size = 25, face = "bold", hjust = 0.5))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/OPLA LF vs HF/graphs/MAPK8.png')

ggbarplot(qPCR_summary, x = "FA", "MAPK9",
       add = "mean_se", error.plot = "upper_errorbar", palette = "npg", legend = "none", fill = "FA",   xlab = "OPLA Concentration (uM)", ylab = "Deltadelta Ct", title = "JNK2") +
  scale_y_continuous(expand = c(0,0)) +
theme(axis.text.x = element_text(color = "grey20", size = 16),
axis.text.y = element_text(color = "grey20", size = 16),
axis.title.x = element_text(color = "grey20", size = 18),
axis.title.y = element_text(color = "grey20", size = 18),
plot.title = element_text(color = "grey20", size = 25, face = "bold", hjust = 0.5))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/OPLA LF vs HF/graphs/MAPK9.png')

ggbarplot(qPCR_summary, x = "FA", "NFKB1",
       add = "mean_se", error.plot = "upper_errorbar", palette = "npg", legend = "none", fill = "FA",   xlab = "OPLA Concentration (uM)", ylab = "Deltadelta Ct", title = "NFKB1") +
  scale_y_continuous(expand = c(0,0)) +
theme(axis.text.x = element_text(color = "grey20", size = 16),
axis.text.y = element_text(color = "grey20", size = 16),
axis.title.x = element_text(color = "grey20", size = 18),
axis.title.y = element_text(color = "grey20", size = 18),
plot.title = element_text(color = "grey20", size = 25, face = "bold", hjust = 0.5))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/OPLA LF vs HF/graphs/NFKB1.png')
```

